<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-05T11:05:27 MEZ" name="Default suite" finished-at="2024-11-05T11:05:27 MEZ" duration-ms="70">
    <groups>
    </groups>
    <test started-at="2024-11-05T11:05:27 MEZ" name="Default test" finished-at="2024-11-05T11:05:27 MEZ" duration-ms="70">
      <class name="exceptionsTesting.Test_Aufgabe3">
        <test-method signature="testParseint()[pri:0, instance:exceptionsTesting.Test_Aufgabe3@41e1e210]" started-at="2024-11-05T11:05:27 MEZ" name="testParseint" finished-at="2024-11-05T11:05:27 MEZ" duration-ms="13" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testParseint -->
        <test-method signature="testParseint2()[pri:0, instance:exceptionsTesting.Test_Aufgabe3@41e1e210]" started-at="2024-11-05T11:05:27 MEZ" name="testParseint2" finished-at="2024-11-05T11:05:27 MEZ" duration-ms="1" status="FAIL">
          <exception class="exceptionsTesting.InvalidNumberException">
            <message>
              <![CDATA[Keine Zahl eingegeben!]]>
            </message>
            <full-stacktrace>
              <![CDATA[exceptionsTesting.InvalidNumberException: Keine Zahl eingegeben!
at exceptionsTesting.Aufgabe3.parseInt(Aufgabe3.java:9)
at exceptionsTesting.Test_Aufgabe3.testParseint2(Test_Aufgabe3.java:17)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- exceptionsTesting.InvalidNumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testParseint2 -->
      </class> <!-- exceptionsTesting.Test_Aufgabe3 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
